# Generated by Django 4.1.5 on 2025-07-08 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_listing_watchlist_comment_bid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='lisiting',
            new_name='listing',
        ),
    ]
